import { Application } from "@/types/application";

export const applications: Application[] = [
  {
    id: 1,
    company: "SAP",
    position: "Frontend Developer",
    status: "interview",
    location: "Berlin",
    source: "Linkedin",
    appliedAt: "2026-06-01",
  },
  {
    id: 2,
    company: "Decathlon",
    position: "Sales Assistant",
    status: "applied",
    location: "Berlin",
    source: "Company site",
    appliedAt: "2026-05-11",
  },

  {
    id: 3,
    company: "SAP",
    position: "Frontend Developer",
    status: "interview",
    location: "Berlin",
    source: "Linkedin",
    appliedAt: "2026-06-01",
  },
  {
    id: 4,
    company: "SAP",
    position: "Frontend Developer",
    status: "interview",
    location: "Berlin",
    source: "Linkedin",
    appliedAt: "2026-06-01",
  },
  {
    id: 5,
    company: "SAP",
    position: "Frontend Developer",
    status: "interview",
    location: "Berlin",
    source: "Linkedin",
    appliedAt: "2026-06-01",
  },
  {
    id: 6,
    company: "SAP",
    position: "Frontend Developer",
    status: "interview",
    location: "Berlin",
    source: "Linkedin",
    appliedAt: "2026-06-01",
  },
  {
    id: 7,
    company: "SAP",
    position: "Frontend Developer",
    status: "interview",
    location: "Berlin",
    source: "Linkedin",
    appliedAt: "2026-06-01",
  },
  {
    id: 8,
    company: "SAP",
    position: "Frontend Developer",
    status: "interview",
    location: "Berlin",
    source: "Linkedin",
    appliedAt: "2026-06-01",
  },
];
